### ISSUE TITLE
[SETTING] 프로젝트 초기 셋팅

### ISSUE THREAD

**Issue by sung-silver** [wanted-pre-onboarding-backend-team-7/AROUND-MEAL#1]
## 🍚 Description

- 프로젝트 초기 셋팅을 진행합니다

## 🍚 To-do

- [x] pre-commit 설정
- [x] 패키지 구조 설정
- [x] issue-template, pr-template 적용

## 🍚 ETC

- 2024.08.27
