### ISSUE TITLE
[FEAT] 맛집 상세목록 조회 구현

### ISSUE THREAD

**Issue by bbwest0709** [wanted-pre-onboarding-backend-team-7/AROUND-MEAL#35]
## 🍚 Description

- 맛집 상세목록 조회 구현

## 🍚 To-do

- [ ] Rating 엔티티 생성일자 필드 추가
- [ ] DTO 매핑 메서드 구현
- [ ] Rating 리스트 최신순 정렬 적용
- [ ] 적절한 예외 처리 구현

## 🍚 ETC

- RatingAverage 필드 조회 미구현(Rating 기능 완료 후 추가 예정)
