### ISSUE TITLE
[TEST] 사용자 설정 테스트

### ISSUE THREAD

**Issue by bbwest0709** [wanted-pre-onboarding-backend-team-7/AROUND-MEAL#71]
## 🍚 Description

- 사용자 설정 테스트

## 🍚 To-do

- [x] 회원 실시간 위치 정보 Redis 저장 테스트
- [x] 회원 실시간 위치 정보 Redis 조회 테스트
- [x] 회원 실시간 위치 정보 DTO 변환 테스트
- [x] 회원 정적인 위치 정보 DB 저장 테스트
- [x] 회원 정적인 위치 정보 DB 조회 테스트

## 🍚 ETC

- 24.08.31
