### ISSUE TITLE
[FEAT] 맛집 상세정보 고도화 API 구현(평가 수 특정 이상)

### ISSUE THREAD

**Issue by yony-k** [wanted-pre-onboarding-backend-team-7/AROUND-MEAL#76]
## 🍚 Description

- 특정 평점 이상의 맛집만 캐싱해놓는 API 구현

## 🍚 To-do

- [ ] Redis에 맛집 상세정보 업로드 구현
- [ ] 리포지토리에서 필터링해서 엔티티 목록 가져오기 구현
- [ ] 기존 Redis 기록과 DB의 새로운 기록 교체 구현

## 🍚 ETC

- 2024.09.01
