### ISSUE TITLE
[TEST] 맛집 상세 조회 및 조회수 캐싱 기능 테스트

### ISSUE THREAD

**Issue by bbwest0709** [wanted-pre-onboarding-backend-team-7/AROUND-MEAL#89]
## 🍚 Description

- 맛집 상세 조회 및 조회수 캐싱 기능 테스트

## 🍚 To-do

- [x] 특정 맛집의 전체 및 시간별 조회수 증가 테스트
- [x] 조회수 데이터가 존재하지 않을 때, 0 반환 테스트
- [x] 조회수 데이터가 존재할 때 전체 조회수 반환 테스트
- [x] 1시간 기준 조회수 N개 이상 캐싱 처리
- [x] 1시간 기준 조회수 초기화 테스트
- [x] 조회수 기준으로 맛집 상세 목록 정렬 테스트
