### ISSUE TITLE
[FIX] 데이터 파이프라인 개선 및 원본 데이터 유효성 검증 추가

### ISSUE THREAD

**Issue by Hajin74** [wanted-pre-onboarding-backend-team-7/AROUND-MEAL#90]
## 🍚 Description

- 좌표가 없는 음식점들은 저장하지 않기
- 전화번호 공백 제거하기
- PAGE_SIZE 단위로 데이터 수집 후 바로 가공하도록 수정

## 🍚 To-do

- [ ] 좌표가 없는 음식점들은 저장하지 않기
- [ ] 전화번호 공백 제거하기
- [ ] PAGE_SIZE 단위로 데이터 수집 후 바로 가공하도록 수정

## 🍚 ETC

- 24.09.02
