### ISSUE TITLE
[TEST] 평가 생성 API 테스트 코드 추가

### ISSUE THREAD

**Issue by sonaanweb** [wanted-pre-onboarding-backend-team-7/AROUND-MEAL#99]
## 🍚 Description

- 테스트 코드를 추가합니다

## 🍚 To-do

- [x] 평가 생성 API 테스트 코드 추가
- [x] 사용하지 않는 코드 삭제
- [ ] 캐시 만료기간 수정
